# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(size=(7,7))
tensor_A

tensor([[9.9129e-01, 3.5084e-01, 8.2852e-01, 7.8978e-01, 1.8979e-01, 8.5991e-02,
         5.2319e-01],
        [6.8814e-01, 3.4712e-01, 3.9464e-02, 3.3295e-01, 8.3972e-01, 5.3513e-02,
         2.1924e-01],
        [7.2129e-01, 8.6764e-01, 1.6197e-01, 3.2538e-04, 3.3430e-01, 3.3216e-02,
         9.6332e-01],
        [6.8387e-01, 6.2016e-01, 9.4606e-01, 3.5394e-01, 6.3453e-01, 6.6871e-01,
         6.1857e-02],
        [6.1429e-01, 8.6074e-01, 2.9160e-01, 4.0329e-02, 5.8048e-01, 5.4096e-01,
         5.8314e-01],
        [7.6217e-01, 5.4622e-01, 5.2065e-03, 1.1232e-01, 7.4399e-01, 5.3590e-01,
         4.7454e-01],
        [1.3407e-02, 5.8439e-01, 2.4002e-02, 7.2887e-01, 8.6028e-01, 7.8329e-01,
         1.3371e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(size=(1, 7))

# Perform matrix multiplication
torch.mm(tensor_A, tensor_B.T)

tensor([[2.9378],
        [2.0467],
        [1.8920],
        [2.8333],
        [2.0964],
        [1.9693],
        [1.9796]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(seed=0)

# Create two random tensors
tensor_A = torch.rand(size=(7,7))
tensor_B = torch.rand(size=(1,7))
# Matrix multiply tensors

torch.mm(tensor_A, tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
tensor_A = torch.rand(2,3).cuda()
tensor_B = torch.rand(2,3).cuda()

tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
output = torch.mm(tensor_A, tensor_B.T)

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(output.max())
# Find min
print(output.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(output.argmax())

# Find arg min
print(output.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(seed=7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor)
print(squeezed_tensor)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
